// tailwind.config.js — Forge design system bridge
// Phase 1: az-* aliases kept temporarily for backward compat with existing pages.
// They map to Forge tokens and will be removed in Phase 8 (Purge).
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Forge tokens (the real system) ──
        bg:            'var(--f-bg)',
        surface:       'var(--f-surface)',
        'surface-sunken':'var(--f-surface-sunken)',
        'surface-raised':'var(--f-surface-raised)',
        rail:          'var(--f-rail)',
        ink:           'var(--f-text)',
        'ink-2':       'var(--f-text-2)',
        'ink-3':       'var(--f-text-3)',
        'ink-inv':     'var(--f-text-inv)',
        line:          'var(--f-line)',
        'line-strong': 'var(--f-line-strong)',
        'line-contrast':'var(--f-line-contrast)',
        accent:        'var(--f-accent)',
        'accent-text': 'var(--f-accent-text)',
        tint:          'var(--f-tint-color)',
        ok:'var(--f-ok)','ok-bg':'var(--f-ok-bg)',
        warn:'var(--f-warn)','warn-bg':'var(--f-warn-bg)',
        bad:'var(--f-bad)','bad-bg':'var(--f-bad-bg)',
        info:'var(--f-info)','info-bg':'var(--f-info-bg)',

        // ── Legacy az-* aliases (removed in Phase 8) ──
        'az-bg':             'var(--f-bg)',
        'az-bg-alt':         'var(--f-surface-sunken)',
        'az-surface':        'var(--f-surface)',
        'az-surface-solid':  'var(--f-surface)',
        'az-border':         'var(--f-line)',
        'az-border-strong':  'var(--f-line-strong)',
        'az-text':           'var(--f-text)',
        'az-text-secondary': 'var(--f-text-2)',
        'az-text-muted':     'var(--f-text-3)',
        'az-accent':         'var(--f-tint-color)',
        'az-accent-hover':   'var(--f-tint-color)',
        'az-accent-subtle':  'var(--f-surface-sunken)',
        'az-accent-border':  'var(--f-line-strong)',
        'az-success':        'var(--f-ok)',
        'az-success-subtle': 'var(--f-ok-bg)',
        'az-warning':        'var(--f-warn)',
        'az-warning-subtle': 'var(--f-warn-bg)',
        'az-danger':         'var(--f-bad)',
        'az-danger-subtle':  'var(--f-bad-bg)',
        'az-info':           'var(--f-info)',
        'az-card':           'var(--f-surface)',
        'az-card-elevated':  'var(--f-surface-raised)',
        'az-black':          'var(--f-ink-900)',
        'az-emerald':        'var(--f-ok)',
        'az-blue':           'var(--f-info)',
        'az-purple':         'var(--f-tint-color)',
        'az-amber':          'var(--f-warn)',
        'az-red':            'var(--f-bad)',
        'az-cyan':           'var(--f-info)',
        'az-teal':           'var(--f-info)',

        // shadcn/ui compat (mapped to Forge)
        background: 'var(--f-bg)',
        foreground: 'var(--f-text)',
        card: { DEFAULT: 'var(--f-surface)', foreground: 'var(--f-text)' },
        popover: { DEFAULT: 'var(--f-surface)', foreground: 'var(--f-text)' },
        primary: { DEFAULT: 'var(--f-accent)', foreground: 'var(--f-accent-text)' },
        secondary: { DEFAULT: 'var(--f-surface-sunken)', foreground: 'var(--f-text-2)' },
        muted: { DEFAULT: 'var(--f-surface-sunken)', foreground: 'var(--f-text-3)' },
        accent: { DEFAULT: 'var(--f-surface-sunken)', foreground: 'var(--f-text)' },
        destructive: { DEFAULT: 'var(--f-bad)', foreground: '#fff' },
        border: 'var(--f-line)',
        input: 'var(--f-line-strong)',
        ring: 'var(--f-line-contrast)',
      },
      fontFamily: { sans:['Inter','ui-sans-serif','system-ui','sans-serif'],
                    mono:['JetBrains Mono','ui-monospace','monospace'] },
      fontSize: {
        xs:  ['11px',{lineHeight:'16px'}],
        sm:  ['12px',{lineHeight:'18px'}],
        base:['13px',{lineHeight:'19px'}],
        md:  ['13px',{lineHeight:'19px'}],
        lg:  ['15px',{lineHeight:'22px'}],
        xl:  ['19px',{lineHeight:'26px',letterSpacing:'-0.022em'}],
        '2xl':['24px',{lineHeight:'30px',letterSpacing:'-0.028em'}],
        '3xl':['30px',{lineHeight:'36px',letterSpacing:'-0.032em'}],
      },
      borderRadius: { DEFAULT:'6px', sm:'4px', md:'6px', lg:'8px', xl:'12px',
                      '2xl':'16px',
                      'az-lg':'20px','az-md':'14px','az-sm':'10px','az-pill':'999px' },
      spacing: { row:'32px','row-sm':'26px','row-lg':'38px',
                 rail:'52px', panel:'212px', topbar:'48px' },
      boxShadow: {
        flush:'var(--f-d-flush)', d1:'var(--f-d-1)',
        d2:'var(--f-d-2)', d3:'var(--f-d-3)', bevel:'var(--f-bevel)',
        // legacy aliases
        'az-card':'var(--f-d-1)', 'az-card-hover':'var(--f-d-2)',
        'az-glass':'var(--f-d-2)', 'az-modal':'var(--f-d-3)',
        'az-focus':'0 0 0 3px color-mix(in oklab, var(--f-line-contrast) 14%, transparent)',
      },
      backdropBlur: { xs:'2px', glass:'20px' },
      keyframes: {
        'fade-in':   { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in':  { from: { transform: 'translateX(-10px)', opacity: '0' }, to: { transform: 'translateX(0)', opacity: '1' } },
        'slide-in-right': { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        'scale-in':  { from: { transform: 'scale(0.97)', opacity: '0' }, to: { transform: 'scale(1)', opacity: '1' } },
        'pulse-dot': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
        shimmer:     { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      animation: {
        'fade-in':   'fade-in 0.25s ease-out',
        'slide-in':  'slide-in 0.25s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'scale-in':  'scale-in 0.2s ease-out',
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
        shimmer:     'shimmer 1.6s linear infinite',
      },
      transitionTimingFunction: { out:'var(--f-e-out)', io:'var(--f-e-io)' },
    },
  },
  plugins: [],
}
