/**
 * INSTRUMENT — Tailwind is used for layout utilities ONLY (flex, grid, gap, spacing).
 * Color, shadow, radius, and typography come from instrument.css CSS custom properties.
 *
 * Compatibility shim: maps legacy Forge Tailwind color names to Instrument CSS variables
 * so the ~16 screens still using bg-surface/text-ink-2/etc. keep rendering.
 * This shim is deleted once every screen migrates to instrument .i-* classes.
 */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      // ── Instrument compat shim (maps old Forge token names → Instrument vars) ──
      colors: {
        bg:            'var(--bg)',
        surface:       'var(--surface)',
        'surface-sunken':'var(--surface-sunk)',
        'surface-raised':'var(--surface-raise)',
        rail:          'var(--chrome)',
        ink:           'var(--text)',
        'ink-2':       'var(--text-2)',
        'ink-3':       'var(--text-3)',
        'ink-inv':     'var(--text-inv)',
        line:          'var(--line)',
        'line-strong': 'var(--line-firm)',
        'line-contrast':'var(--line-hard)',
        accent:        'var(--accent)',
        'accent-text': 'var(--accent-text)',
        tint:          'var(--accent)',
        ok:'var(--go)',   'ok-bg':'var(--go-bg)',
        warn:'var(--hold)','warn-bg':'var(--hold-bg)',
        bad:'var(--stop)', 'bad-bg':'var(--stop-bg)',
        info:'var(--cool)','info-bg':'var(--cool-bg)',
        'az-bg':             'var(--bg)',
        'az-bg-alt':         'var(--surface-sunk)',
        'az-surface':        'var(--surface)',
        'az-surface-solid':  'var(--surface)',
        'az-border':         'var(--line)',
        'az-border-strong':  'var(--line-firm)',
        'az-text':           'var(--text)',
        'az-text-secondary': 'var(--text-2)',
        'az-text-muted':     'var(--text-3)',
        'az-accent':         'var(--accent)',
        'az-accent-hover':   'var(--accent)',
        'az-accent-subtle':  'var(--surface-sunk)',
        'az-accent-border':  'var(--line-firm)',
        'az-success':        'var(--go)',
        'az-success-subtle': 'var(--go-bg)',
        'az-warning':        'var(--hold)',
        'az-warning-subtle': 'var(--hold-bg)',
        'az-danger':         'var(--stop)',
        'az-danger-subtle':  'var(--stop-bg)',
        'az-info':           'var(--cool)',
        'az-card':           'var(--surface)',
        'az-card-elevated':  'var(--surface-raise)',
        'az-black':          'var(--text)',
        'az-emerald':        'var(--go)',
        'az-blue':           'var(--cool)',
        'az-purple':         'var(--accent)',
        'az-amber':          'var(--hold)',
        'az-red':            'var(--stop)',
        'az-cyan':           'var(--cool)',
        'az-teal':           'var(--cool)',
        background: 'var(--bg)',
        foreground: 'var(--text)',
        card: { DEFAULT: 'var(--surface)', foreground: 'var(--text)' },
        popover: { DEFAULT: 'var(--surface)', foreground: 'var(--text)' },
        primary: { DEFAULT: 'var(--accent)', foreground: 'var(--accent-text)' },
        secondary: { DEFAULT: 'var(--surface-sunk)', foreground: 'var(--text-2)' },
        muted: { DEFAULT: 'var(--surface-sunk)', foreground: 'var(--text-3)' },
        destructive: { DEFAULT: 'var(--stop)', foreground: '#fff' },
        border: 'var(--line)',
        input: 'var(--line-firm)',
        ring: 'var(--line-hard)',
      },
      fontFamily: { sans:['Geist','ui-sans-serif','system-ui','sans-serif'],
                    mono:['Geist Mono','ui-monospace','monospace'] },
      fontSize: {
        xs:  ['11px',{lineHeight:'16px'}],
        sm:  ['12px',{lineHeight:'18px'}],
        base:['13px',{lineHeight:'19px'}],
        md:  ['13px',{lineHeight:'19px'}],
        lg:  ['15px',{lineHeight:'22px'}],
        xl:  ['19px',{lineHeight:'26px',letterSpacing:'-0.022em'}],
        '2xl':['24px',{lineHeight:'30px',letterSpacing:'-0.028em'}],
        '3xl':['30px',{lineHeight:'36px',letterSpacing:'-0.032em'}],
      },
      borderRadius: { DEFAULT:'6px', sm:'4px', md:'6px', lg:'8px', xl:'12px',
                      '2xl':'16px',
                      'az-lg':'20px','az-md':'14px','az-sm':'10px','az-pill':'999px' },
      spacing: { row:'32px','row-sm':'26px','row-lg':'38px',
                 rail:'52px', panel:'212px', topbar:'48px' },
      boxShadow: {
        flush:'0 1px 0 0 var(--line-firm)', d1:'var(--d1)',
        d2:'var(--d2)', d3:'var(--d3)', bevel:'var(--bevel)',
        'az-card':'var(--d1)', 'az-card-hover':'var(--d2)',
        'az-glass':'var(--d2)', 'az-modal':'var(--d3)',
        'az-focus':'0 0 0 3px color-mix(in oklab, var(--line-hard) 14%, transparent)',
      },
      backdropBlur: { xs:'2px', glass:'20px' },
      keyframes: {
        'fade-in':   { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in':  { from: { transform: 'translateX(-10px)', opacity: '0' }, to: { transform: 'translateX(0)', opacity: '1' } },
        'slide-in-right': { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        'scale-in':  { from: { transform: 'scale(0.97)', opacity: '0' }, to: { transform: 'scale(1)', opacity: '1' } },
        'pulse-dot': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
        shimmer:     { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      animation: {
        'fade-in':   'fade-in 0.25s ease-out',
        'slide-in':  'slide-in 0.25s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'scale-in':  'scale-in 0.2s ease-out',
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
        shimmer:     'shimmer 1.6s linear infinite',
      },
    },
  },
  plugins: [],
}
