import { useMemo, useState } from 'react';
import { Copy, ExternalLink, Plus, Redo2, Trash2, Undo2 } from 'lucide-react';
import StudioLayerTree from './StudioLayerTree';
import StudioInspector from './StudioInspector';
import { STUDIO_NODE_TYPES } from '@/lib/storefrontStudioModel';
import { useStorefrontStudio } from '@/hooks/useStorefrontStudio';

const LABELS = { page:'Page', section:'Section', stack:'Stack', row:'Row', column:'Column', grid:'Grid', overlay:'Overlay', hero:'Hero', 'product-grid':'Product Grid', 'product-carousel':'Product Carousel', 'product-card':'Product Card', 'category-rail':'Category Rail', button:'Button', 'icon-button':'Icon Button', text:'Text', image:'Image', video:'Video', rating:'Rating', reviews:'Reviews', contact:'Contact', location:'Location', promo:'Promotion', social:'Social', spacer:'Spacer', divider:'Divider' };
const CONTAINERS = new Set(['page','section','stack','row','column','grid','overlay','product-carousel','category-rail']);
const buttonClass = 'rounded-lg border px-2.5 py-1.5 text-[11px] font-semibold disabled:opacity-40';

function PreviewNode({ node, document, selection, onSelect }) {
  if (!node || node.layout?.visibility === false) return null;
  const p = node.props || {}, s = node.style || {}, l = node.layout || {};
  const selected = selection.includes(node.id);
  const children = (node.children || []).map((id) => document.nodes[id]).filter(Boolean);
  const box = { padding: l.padding ?? 8, opacity: s.opacity ?? 1, borderRadius: s.radius === 'pill' ? 999 : s.radius === 'large' ? 20 : s.radius === 'small' ? 6 : 12, border: selected ? '2px solid var(--accent)' : '1px solid transparent' };
  let content = children.length ? <div className="grid gap-2" style={{ gridTemplateColumns: node.type === 'grid' ? `repeat(${Math.max(1, p.columns || 2)}, minmax(0, 1fr))` : undefined }}>{children.map((child) => <PreviewNode key={child.id} node={child} document={document} selection={selection} onSelect={onSelect} />)}</div> : <div className="min-h-6 text-xs" style={{ color: 'var(--text-2)' }}>{LABELS[node.type] || node.type}</div>;
  if (node.type === 'hero') content = <div className="min-h-32 rounded-xl p-4 flex flex-col justify-end" style={{ color:'#fff', background:p.mediaUrl ? `url(${p.mediaUrl}) center/cover` : 'linear-gradient(135deg,var(--accent),#191919)' }}><strong className="text-xl">{p.title || 'Your business'}</strong><span className="text-xs opacity-80">{p.subtitle || 'Welcome.'}</span></div>;
  if (node.type === 'text') content = <p className="m-0 text-sm leading-6" style={{ color:s.textColor || 'var(--text)' }}>{p.value || p.text || 'Text block'}</p>;
  if (node.type === 'button' || node.type === 'icon-button') content = <div className="rounded-xl px-4 py-2.5 text-center text-sm font-bold" style={{ background:s.fill || 'var(--accent)', color:s.textColor || '#fff' }}>{p.label || 'Button'}</div>;
  if (node.type === 'image') content = p.mediaUrl ? <img src={p.mediaUrl} alt={p.alt || ''} className="w-full max-h-40 object-cover rounded-xl" /> : <div className="h-24 grid place-items-center rounded-xl" style={{ background:'var(--surface-sunk)', color:'var(--text-3)' }}>Image</div>;
  if (node.type === 'promo') content = <div className="rounded-xl p-3" style={{ background:s.fill || 'color-mix(in srgb,var(--accent) 10%,var(--surface))' }}><strong>{p.title || 'Special offer'}</strong><div className="mt-1 text-xs" style={{ color:'var(--text-2)' }}>{p.subtitle || 'Promotion'}</div>{p.ctaText && <div className="mt-2 text-xs font-bold" style={{ color:'var(--accent)' }}>{p.ctaText}</div>}</div>;
  if (node.type === 'product-grid' || node.type === 'product-carousel' || node.type === 'category-rail') content = <div><div className="mb-2 text-sm font-bold">{p.title || LABELS[node.type]}</div><div className="grid grid-cols-2 gap-2">{Array.from({ length: Math.min(p.maxItems || 4, 4) }).map((_, i) => <div key={i} className="rounded-lg border p-2" style={{ borderColor:'var(--line)', background:'var(--surface-sunk)' }}><div className="h-12 rounded-md" style={{ background:'color-mix(in srgb,var(--accent) 10%,var(--surface))' }} /><div className="mt-2 h-1.5 w-2/3 rounded" style={{ background:'var(--line)' }} /></div>)}</div></div>;
  return <div onClick={(e) => { e.stopPropagation(); onSelect(node.id, e); }} className="relative" style={box}>{selected && <div className="absolute -top-2 left-2 rounded bg-[var(--accent)] px-1.5 py-0.5 text-[9px] font-bold text-white">{LABELS[node.type] || node.type}</div>}{content}</div>;
}

export default function StorefrontStudioV2({ draft, saveDraft, business, onClose }) {
  const studio = useStorefrontStudio({ draft, saveDraft });
  const [tab, setTab] = useState('content');
  const [filter, setFilter] = useState('');
  const node = studio.selection[0] ? studio.document.nodes[studio.selection[0]] : null;
  const palette = useMemo(() => STUDIO_NODE_TYPES.filter((type) => !filter || type.includes(filter.toLowerCase())), [filter]);
  const select = (id, e) => studio.setSelection((e?.metaKey || e?.ctrlKey) ? [...new Set([...studio.selection, id])] : [id]);
  const add = (type) => studio.addNode(type, node && CONTAINERS.has(node.type) ? node.id : null);
  const root = studio.document.pages[0]?.root || [];

  return <div className="fixed inset-0 z-50 flex flex-col overflow-hidden" style={{ background:'var(--f-bg)', color:'var(--f-text)' }}>
    <header className="flex min-h-14 items-center justify-between gap-3 border-b px-4" style={{ borderColor:'var(--f-line)', background:'var(--f-surface)' }}><div className="flex items-center gap-3"><strong className="text-sm">Storefront Studio</strong><span className="rounded-full px-2 py-1 text-[10px]" style={{ background:'var(--f-surface-sunken)', color:'var(--f-text-3)' }}>Semantic V2</span><span className="text-[11px]" style={{ color:'var(--f-text-3)' }}>{business?.businessName || ''}</span></div><div className="flex items-center gap-2"><button className={buttonClass} disabled={!studio.canUndo} onClick={studio.undo}><Undo2 className="mr-1 inline h-3.5 w-3.5"/>Undo</button><button className={buttonClass} disabled={!studio.canRedo} onClick={studio.redo}><Redo2 className="mr-1 inline h-3.5 w-3.5"/>Redo</button><button className={buttonClass} disabled={!node} onClick={() => studio.duplicate()}><Copy className="mr-1 inline h-3.5 w-3.5"/>Duplicate</button><button className={buttonClass} disabled={!node} onClick={() => studio.remove()}><Trash2 className="mr-1 inline h-3.5 w-3.5"/>Delete</button><button className="rounded-lg px-3 py-1.5 text-[11px] font-bold text-white" style={{ background:'var(--accent)' }} onClick={() => studio.save()}><ExternalLink className="mr-1 inline h-3.5 w-3.5"/>Save</button><button className={buttonClass} onClick={onClose}>Close</button></div></header>
    <div className="grid min-h-0 flex-1 grid-cols-[230px_minmax(360px,1fr)_310px]">
      <aside className="min-h-0 overflow-y-auto border-r p-3" style={{ borderColor:'var(--f-line)', background:'var(--f-surface-sunken)' }}><div className="mb-2 text-[10px] font-bold uppercase tracking-[.15em]" style={{ color:'var(--f-text-3)' }}>Components</div><input value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="Search components" className="mb-3 w-full rounded-lg border px-3 py-2 text-xs" style={{ borderColor:'var(--f-line)', background:'var(--f-surface)', color:'var(--f-text)' }}/><div className="grid grid-cols-2 gap-2">{palette.map((type) => <button key={type} className="rounded-lg border px-2 py-2 text-left text-[10px] font-semibold" style={{ borderColor:'var(--f-line)', background:'var(--f-surface)' }} draggable onDragStart={(e) => e.dataTransfer.setData('application/x-azm-studio-node', type)} onClick={() => add(type)}><Plus className="mr-1 inline h-3 w-3"/>{LABELS[type] || type}</button>)}</div><div className="mt-5 border-t pt-4" style={{ borderColor:'var(--f-line)' }}><div className="mb-2 text-[10px] font-bold uppercase tracking-[.15em]" style={{ color:'var(--f-text-3)' }}>Layers</div><StudioLayerTree document={studio.document} selection={studio.selection} onSelectionChange={studio.setSelection} onMoveNode={studio.move} onToggleVisibility={studio.setVisibility} onToggleLock={studio.setLocked}/></div></aside>
      <main className="min-h-0 overflow-auto p-6" style={{ background:'var(--f-bg)' }}><div className="mx-auto max-w-[760px]"><div className="mb-4 flex items-center justify-between"><div><div className="text-xs font-semibold">Phone stage</div><div className="text-[11px]" style={{ color:'var(--f-text-3)' }}>Drag a component onto the stage to add it. Select a layer to edit content, style, layout, actions and breakpoints.</div></div><span className="text-[10px]" style={{ color:'var(--f-text-3)' }}>{Object.keys(studio.document.nodes).length} layers</span></div><div className="mx-auto w-[390px] max-w-full rounded-[30px] border-[8px] p-2 shadow-2xl" style={{ borderColor:'#161616', background:'#111' }}><div className="overflow-hidden rounded-[22px] bg-white" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); const type=e.dataTransfer.getData('application/x-azm-studio-node'); if(type) add(type); }}><div className="flex justify-between px-4 py-2 text-[10px]" style={{ background:'var(--surface-sunk)', color:'var(--text-3)' }}><span>{business?.businessName || 'Storefront'}</span><span>9:41</span></div><div className="space-y-2 p-2" onClick={() => studio.setSelection([])}>{root.map((id) => <PreviewNode key={id} node={studio.document.nodes[id]} document={studio.document} selection={studio.selection} onSelect={select}/>)}</div></div></div></div></main>
      <aside className="min-h-0 overflow-hidden border-l" style={{ borderColor:'var(--f-line)', background:'var(--f-surface-sunken)' }}><StudioInspector node={node} pages={studio.document.pages} nodeIds={Object.keys(studio.document.nodes)} activeTab={tab} onTabChange={setTab} onPatch={(domain, patch) => node && studio.patchNode(node.id, domain, patch)}/></aside>
    </div>
  </div>;
}
